# Generated by Django 4.1.4 on 2023-01-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Trombinoscope',
            fields=[
                ('year', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True, verbose_name='')),
                ('lastname', models.CharField(max_length=50, null=True, verbose_name='')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='')),
                ('trombinoscope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trombinoscope.trombinoscope')),
            ],
        ),
    ]
