# Generated by Django 4.1.4 on 2023-01-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trombinoscope',
            fields=[
                ('year', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='description')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trombinoscope.category')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpeg', upload_to='')),
                ('firstname', models.CharField(max_length=50, null=True, verbose_name='')),
                ('lastname', models.CharField(max_length=50, null=True, verbose_name='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trombinoscope.role')),
                ('trombinoscope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trombinoscope.trombinoscope')),
            ],
        ),
    ]
