# Generated by Django 4.1.4 on 2023-01-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default', upload_to=''),
        ),
    ]
