# Generated by Django 4.1.4 on 2023-01-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shortname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
