# Generated by Django 4.1.4 on 2023-01-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0004_category_remove_role_type_role_name_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trombinoscope.department'),
        ),
    ]
